"Resource/UI/FortFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"200"
		"tall"					"125"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnFortSolo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFortSolo"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFreeOnline"
		"navDown"				"BtnFortFriends"
		"labelText"				"PLAY SOLO"
		"style"					"FlyoutMenuButton"
		"command"				"SoloPlay_hd4lfort"
	}

	"BtnFortFriends"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFortFriends"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFortSolo"
		"navDown"				"BtnFortOnline"
		"labelText"				"PLAY WITH FRIENDS"
		"style"					"FlyoutMenuButton"
		"command"				"FriendsMatch_hd4lfort"
	}

	"BtnFortOnline"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFortOnline"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFortFriends"
		"navDown"				"BtnFreeSolo"
		"labelText"				"PLAY ONLINE"
		"style"					"FlyoutMenuButton"
		"command"				"CustomMatch_hd4lfort"
	}
	"BtnFreeSolo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFreeSolo"
		"xpos"					"0"
		"ypos"					"65"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFortOnline"
		"navDown"				"BtnFreeFriends"
		"labelText"				"FREEBUILD SOLO"
		"style"					"FlyoutMenuButton"
		"command"				"SoloPlay_hd4lfreebuild"
	}

	"BtnFreeFriends"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFreeFriends"
		"xpos"					"0"
		"ypos"					"85"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFreeSolo"
		"navDown"				"BtnFreeOnline"
		"labelText"				"FREEBUILD WITH FRIENDS"
		"style"					"FlyoutMenuButton"
		"command"				"FriendsMatch_hd4lfreebuild"
	}

	"BtnFreeOnline"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnFreeOnline"
		"xpos"					"0"
		"ypos"					"105"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnFreeFriends"
		"navDown"				"BtnFortSolo"
		"labelText"				"FREEBUILD ONLINE"
		"style"					"FlyoutMenuButton"
		"command"				"CustomMatch_hd4lfreebuild"
	}
}
