"Resource/UI/HD4LSettingsFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"220"
		"tall"					"85"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnHD4LAddons"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LAddons"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"190"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LMultiplayer"
		"navDown"				"BtnHD4LKeys"
		"labelText"				"ADD-ONS"
		"style"					"FlyoutMenuButton"
		"command"				"Addons"
	}

	"BtnHD4LKeys"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LKeys"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"190"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LAddons"
		"navDown"				"BtnHD4LAudioVideo"
		"labelText"				"KEYBOARD / MOUSE"
		"style"					"FlyoutMenuButton"
		"command"				"KeyboardMouse"
	}

	"BtnHD4LAudioVideo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LAudioVideo"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"190"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LKeys"
		"navDown"				"BtnHD4LMultiplayer"
		"labelText"				"AUDIO / VIDEO"
		"style"					"FlyoutMenuButton"
		"command"				"AudioVideo"
	}

	"BtnHD4LMultiplayer"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LMultiplayer"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"190"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LAudioVideo"
		"navDown"				"BtnHD4LAddons"
		"labelText"				"MULTIPLAYER"
		"style"					"FlyoutMenuButton"
		"command"				"MultiplayerSettings"
	}

}
