"Resource/UI/HD4LFlyout.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"200"
		"tall"					"185"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}

	"BtnHD4LSolo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LSolo"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LSettingsEntry"
		"navDown"				"BtnHD4LFriends"
		"labelText"				"PLAY SOLO"
		"style"					"FlyoutMenuButton"
		"command"				"SoloPlay_hd4l"
	}

	"BtnHD4LFriends"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LFriends"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LSolo"
		"navDown"				"BtnHD4LOnline"
		"labelText"				"PLAY WITH FRIENDS"
		"style"					"FlyoutMenuButton"
		"command"				"FriendsMatch_hd4l"
	}

	"BtnHD4LOnline"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LOnline"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LFriends"
		"navDown"				"BtnHD4LVersusFriends"
		"labelText"				"PLAY ONLINE"
		"style"					"FlyoutMenuButton"
		"command"				"CustomMatch_hd4l"
	}

	"BtnHD4LVersusFriends"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LVersusFriends"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LOnline"
		"navDown"				"BtnHD4LVersusOnline"
		"labelText"				"VERSUS WITH FRIENDS"
		"style"					"FlyoutMenuButton"
		"command"				"FriendsMatch_hd4lversus"
	}

	"BtnHD4LVersusOnline"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LVersusOnline"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LVersusFriends"
		"navDown"				"BtnHD4LFortSolo"
		"labelText"				"VERSUS ONLINE"
		"style"					"FlyoutMenuButton"
		"command"				"CustomMatch_hd4lversus"
	}

	"BtnHD4LFortSolo"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LFortSolo"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LVersusOnline"
		"navDown"				"BtnHD4LFortFriends"
		"labelText"				"FORT SOLO"
		"style"					"FlyoutMenuButton"
		"command"				"SoloPlay_hd4lsurvival"
	}

	"BtnHD4LFortFriends"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LFortFriends"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LFortSolo"
		"navDown"				"BtnHD4LFortOnline"
		"labelText"				"FORT WITH FRIENDS"
		"style"					"FlyoutMenuButton"
		"command"				"FriendsMatch_hd4lsurvival"
	}

	"BtnHD4LFortOnline"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LFortOnline"
		"xpos"					"0"
		"ypos"					"140"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LFortFriends"
		"navDown"				"BtnHD4LSettingsEntry"
		"labelText"				"FORT ONLINE"
		"style"					"FlyoutMenuButton"
		"command"				"CustomMatch_hd4lsurvival"
	}

	"BtnHD4LSettingsEntry"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnHD4LSettingsEntry"
		"xpos"					"0"
		"ypos"					"160"
		"wide"					"170"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnHD4LFortOnline"
		"navDown"				"BtnHD4LSolo"
		"labelText"				"SETTINGS"
		"style"					"FlyoutMenuButton"
		"command"				"FlmHD4LSettings"
	}
}
